Wiki New page modal
chili-epfl/FROG pull request #1680
Opened 2019-05-13 08:17 UTC by ajainuary

This improves the design of the Modal to create a New Page in the wiki.
This also adds operator selector.

2019-05-13 09:10 UTC, houshuang commented
Great start! 

Page Title should autofocus when you open (goal is to be able to do ctrl+n, type something, enter - and you have a new page). 

I would like to make the tabs much more distinct, right now there's almost no visual difference between Settings and Page Title... Can we have a different background for the entire tab row, or a different background for the currently selected tab or what?

I would use the whitespace much more on the first tab - moving page title down a bit, and then the plane and checkboxes much more - have the page title "alone". Also why is there so much gap between the two checkboxes?

The mouseover stays with the item, not the mouse, when you scroll. Anyway this is less urgent, we should find a better solution for mouseover in general.

<img width="1440" alt="Screenshot 2019-05-13 at 11 06 03" src="https://user-images.githubusercontent.com/61575/57609452-35721780-756f-11e9-89f9-7a734eb1c10a.png">

2019-05-17 08:43 UTC, ajainuary commented
Fixed all CSS bugs, wired the Activity form (although some activities have error with delayed state updates)

- [ ]  Need to fix state updates for some activities (like Text Component)
- [ ] Need to wire up Operator Form and Social Plane selection

2019-05-20 06:37 UTC, houshuang submitted a review, later dismissed
Until I get the continuous integration to work again, please run eslint etc locally. 

<img width="743" alt="Screenshot 2019-05-19 at 23 36 44" src="https://user-images.githubusercontent.com/61575/58000921-10aa0280-7a8f-11e9-8dd8-9018738c035c.png">
<img width="700" alt="Screenshot 2019-05-19 at 23 36 38" src="https://user-images.githubusercontent.com/61575/58000922-10aa0280-7a8f-11e9-816b-bcdb67df8d7a.png">

2019-05-20 06:37 UTC, houshuang commented on frog/imports/client/GraphEditor/SidePanel/OperatorPanel/EditOperator.jsx
> +  console.log('Edit');
Make sure to clean up console.log before opening PR

2019-05-20 06:38 UTC, houshuang requested changes
Fix eslint (don't worry about the merge conflict)

2019-05-20 10:18 UTC, ajainuary commented
I have now fixed the linting errors.

2019-05-20 12:37 UTC, merged