Anonymous login for wiki and single activity
chili-epfl/FROG pull request #1696
Opened 2019-05-29 15:39 UTC by ajainuary

Creates an anonymous user when a non-logged in user visits `wiki` or `single_activity`

2019-05-29 17:19 UTC, houshuang commented
This is a good start. 

It doesn't seem like you're setting any flag on the user that they're an automatically generated? Can you add that, and also check in the wiki whether that flag is set, and don't display the username in the menubar if it's an anonymous user.

Also, ideally we would not let anonymous users access other paths... Currently if you go directly to for example /teacher, it will not let you in unless you're logged in or use ?login. However, if you first go to the wiki, and then go to /teacher, it will let you in as that anonymous user...

This is more complex and should be a separate PR. First finish up the first PR with the anonymous ID and removing it from the wiki menu.

Then a separate PR where you try to see if someone is logging in using a token from localSession, and whether that user is an anonymous user, then you should delete the token and treat it like user is not logged in.

You'll have to think a bit about how to do this - maybe the logic should be on the server when you call the login function, maybe you should try to store information in localSession about whether it's an anonymous user or not - see if you can figure it out, otherwise I can help.

2019-05-29 19:44 UTC, ajainuary commented on frog/server/user_accounts.js
> +    isAnonymous: user ? false : true,
Here a flag is set stating that the user is Anonymous

2019-05-29 19:49 UTC, ajainuary commented
https://github.com/chili-epfl/FROG/pull/1696/files#r288737434
(Here is where the flag is set for anonymous user)
Requirements:
- [ ] Hide username for anon user in wiki
- [ ] Don't allow other paths without login

2019-05-30 12:37 UTC, ajainuary commented on frog/server/user_accounts.js
> +      isAnonymous: user ? false : true
The flag for the anonymous user is set here

2019-05-31 14:33 UTC, houshuang requested changes

2019-05-31 14:33 UTC, houshuang commented on frog/imports/client/Wiki/WikiTopNavbar.js
> -
Why did you remove this? it can cause a crash if a component tries to access state without state being initialized.

2019-05-31 14:33 UTC, houshuang commented on frog/server/main.js
> +    fields: { username: 1, isAnonymous: 1, joinedSessions: 1, role: 1 }
good catch

2019-05-31 14:33 UTC, houshuang commented on frog/server/user_accounts.js
> +      isAnonymous: user ? false : true
why not replace with !!user

2019-05-31 15:23 UTC, ajainuary commented on frog/imports/client/Wiki/WikiTopNavbar.js
> -
Component doesn't require a state anymore, I turned it into a functional component now

2019-06-01 17:09 UTC, houshuang commented
@ajainuary When I try the latest version, I see the random student ID in the wiki?

2019-06-03 09:51 UTC, ajainuary commented
I've fixed the typo, please clear the localStorage for testing (close all incognito windows and open again).

2019-06-03 13:49 UTC, houshuang approved these changes

2019-06-03 13:49 UTC, merged