Export activities graph->wiki
chili-epfl/FROG pull request #1747
Opened 2019-06-26 09:09 UTC by houshuang

2019-06-27 15:45 UTC, qgolsteyn requested changes
Left some comments

2019-06-27 15:45 UTC, qgolsteyn commented on frog/imports/client/Wiki/index.js
> +      if (fullPageObj.noNewInstances) {
Nit: perhaps merge the two if statements

2019-06-27 15:45 UTC, qgolsteyn commented on frog/imports/client/Wiki/index.js
>      const mergedObj = Object.assign({}, fullPageObj, instanceObj);
```suggestion
    const mergedObj = {...fullPageObj, ...instanceObj};
```

2019-06-27 15:45 UTC, qgolsteyn commented on frog/imports/client/Wiki/index.js
> +            const instanceName = this.getInstanceNameForUser(fullPageObj);
`getInstanceNameForUser` can return null, maybe we need a null check here

2019-06-27 15:45 UTC, qgolsteyn commented on frog/server/wiki.js
> +export async function importWikiFromFROG(item, object, wiki, page, userId) {
NIT: could use arrow function

2019-06-27 15:45 UTC, qgolsteyn commented on frog/server/wiki.js
> +            }, {}),
NIT assign to variable to help with readability

2019-07-01 10:09 UTC, ajainuary approved these changes
**Testing Done**
Other than the naming issue, everything works as expected

2019-07-01 10:09 UTC, ajainuary commented on frog/imports/client/Wiki/index.js
> +            const instanceName = this.getInstanceNameForUser(fullPageObj);
In theory, it is possible for it to return `null` but it would happen only if the page is p3, and in that case, we will never call the function. Therefore in practice, it should never cause any issues

2019-07-01 10:31 UTC, merged