Add first and second level navigation for activity configuration
chili-epfl/FROG pull request #1763
Opened 2019-07-04 09:29 UTC by qgolsteyn

This PR adds first and second level navigation for activity and operator configuration. This is accomplished by adding a number of new UI to the ObjectField, conditional on its position within the configuration schema. This means that the default behaviour is backward-compatible with how FROG runs today.

_Important notes_
This PR upgrades material-ui meaning there could be changes in UI across FROG

**Testing done**
https://5d1cc7940fd48d596a62ea7c--boring-cray-c77b3b.netlify.com/

**Next steps**
- Preview page has its UI broken. We recommend revisiting this page to fix this issue and to better incorporate the changes in configuration UI.

2019-07-04 10:39 UTC, houshuang requested changes
You knew about the extra whitespace in Preview, but also notice that one of the buttons have been pushed off the viewport.

<img width="388" alt="Screenshot 2019-07-04 at 12 23 36" src="https://user-images.githubusercontent.com/61575/60659814-9d99f700-9e56-11e9-9db5-0981186a2b3a.png">

Should the entire header (General ... ) be clickable to unroll, rather than just the button (that's what I would expect).

How do we specify automatically unrolling a section? If not, I would default to unrolling everything for now. 

Also while you're at it, if you can quickly update the default width of the unrolled ModalCreate in the wiki so that it stays fixed between the three tabs.
Thanks!

2019-07-04 13:11 UTC, qgolsteyn commented
@houshuang Addressed these changes

2019-07-04 14:44 UTC, ajainuary submitted a review, later dismissed
Looks better than existing config, I think sidebar space can be more efficiently utilized
![Space Waste](https://user-images.githubusercontent.com/30972152/60674651-dba91200-9e7a-11e9-949b-8c87fbdd09ad.png)

2019-07-04 14:44 UTC, ajainuary commented on frog-utils/src/FrogForm/components/PrimaryGrouping.jsx
> +            transform: expand ? 'rotate(180deg)' : undefined
Did you intend to have no transform in case `expand` is false? `transform: none` would be more suitable than `undefined`.

2019-07-04 14:44 UTC, ajainuary commented on frog-utils/src/FrogForm/index.js
> +import FrogForm from "./FrogForm";
Why not change the file name?

2019-07-05 07:29 UTC, qgolsteyn commented on frog-utils/src/FrogForm/index.js
> +import FrogForm from "./FrogForm";
Changed, makes more sense

2019-07-05 07:29 UTC, qgolsteyn commented on frog-utils/src/FrogForm/components/PrimaryGrouping.jsx
> +            transform: expand ? 'rotate(180deg)' : undefined
You're right, changed to `rotate(0deg)` to improve readability

2019-07-05 08:01 UTC, merged