Upgrading legacy accounts + Wiki compatibility with legacy accounts
chili-epfl/FROG pull request #1813
Opened 2019-07-31 09:34 UTC by RachitMalik12

This PR adds functionality to upgrade legacy accounts to have a password and display name. Also fixes the logout not being displayed when a legacy account logs into the wiki. 

**Testing instructions**

- Login to a legacy account by using ?login=someusername. Note the user id

- Click upgrade your account on the single activity TopBar or the wiki topbar. Enter some display name, email, password. Check the database and the same user id should have the email associated with it. 
- Try to login using the email you entered 

**Asana task**
https://app.asana.com/0/1121331595459324/1133484398049560/f
https://app.asana.com/0/1129712605359574/1133484398049561/f

2019-07-31 12:03 UTC, houshuang requested changes
Wording: Add email and password to your account. "Upgrade your account" (instead of create etc). 

Making it work in wiki.

2019-07-31 13:44 UTC, qgolsteyn requested changes
Left some comments

2019-07-31 13:44 UTC, qgolsteyn commented on frog/imports/api/users.js
> +  else if (selectedUser.isAnonymous) return 'Anonymous';
The two if statements can be merged using an OR operator

2019-07-31 13:44 UTC, qgolsteyn commented on frog/imports/api/users.js
> +  else if (isVerifiedUser({ selectedUser })) return 'Verified';
BUG: `selectedUser` is not a valid property of type `User`. Why not pass selectedUser directly?

2019-07-31 13:44 UTC, qgolsteyn commented on frog/imports/api/users.js
> +export const userType = (user: User): string => {
```suggestion
export const getUserType = (user: User): string => {
```

2019-07-31 13:44 UTC, qgolsteyn commented on frog/server/accountManagement.js
> +      if (user?.isAnonymous || (user.username && !isVerifiedUser())) {
We should check the user we have

```suggestion
      if (userType(user) === 'Anonymous' || userType(user) === 'Legacy') {
```

2019-08-07 05:30 UTC, houshuang requested changes
An upgraded account is still able to log in using ?login=. It looks like the problem is in api/users isVerifiedUser, it uses getUser, but although it passes a user object, it gets back an anonymous account (I used console log to see what goes in and what comes out). There might be some confusion with the id/obj parameters.

2019-08-07 09:30 UTC, RachitMalik12 commented
> An upgraded account is still able to log in using ?login=. It looks like the problem is in api/users isVerifiedUser, it uses getUser, but although it passes a user object, it gets back an anonymous account (I used console log to see what goes in and what comes out). There might be some confusion with the id/obj parameters.

Yes the parameters were passed the wrong way. On further thought since we have the getUserType function I've decided to keep isVerifiedUser() as a helper. Replaced every instance of isVerifiedUser with getUserType() === 'Verified'.

2019-08-12 07:10 UTC, houshuang commented on frog/imports/client/Wiki/index.js
> +    if (getUserType() === 'Anonymous') {
I like this change :)

2019-08-12 07:14 UTC, houshuang approved these changes

2019-08-12 07:15 UTC, merged