Induc disable sumbit
chili-epfl/FROG pull request #631
Opened 2017-11-01 16:12 UTC by romainAA

The submit button is now disabled when no property is selected.
I still have a problem: the setDisable in the truePanel and falsePanel works well to enable the button,
but when you deselect all properties, you need to refresh the page in order to redisable the button.

2017-11-02 14:51 UTC, lfaucon requested changes

2017-11-02 14:51 UTC, lfaucon commented on ac/ac-induction/src/TestPart/Test.jsx
> +            disabled={disable}
You are doing quite complicated things here. I think you should just have here something like: 
`disabled={tmpList[data.indexCurrent].selectedProperties.length < 1}` 

I think that would be reactive, unlike your current implementation

2017-11-02 14:51 UTC, lfaucon commented on ac/ac-induction/src/TestPart/ResponsePanel.jsx
> +                  tmpList[data.indexCurrent].selectedProperties.length < 0
why `< 0` and not `< 1` ?

2017-11-02 15:14 UTC, romainAA commented
Indeed, at first I had a problem: the button was shown disable, but the clickHandler was still working, that's why I put a state to be able to access it. But I just selected the clickHandler as onClick only if tmpList[data.indexCurrent].selectedProperties.length > 0 and It seems to work well and to be easier.

2017-11-05 14:04 UTC, lfaucon approved these changes

2017-11-05 14:29 UTC, lfaucon approved these changes

2017-11-05 14:29 UTC, merged