Instance preview db
chili-epfl/FROG pull request #637
Opened 2017-11-02 13:40 UTC by romainAA

I added the list of instances to the preview, if you could just check that it is indeed the only place I had to change :)

2017-11-02 13:41 UTC, romainAA commented
(It's build on top of the induc dashboard branch so that I could test my dashboard with it, so please merge inducDashboard before)

2017-11-02 14:23 UTC, lfaucon requested changes

2017-11-02 14:23 UTC, lfaucon commented on frog/imports/ui/Preview/Preview.js
> +                    instances={users.map((u, i) => Math.ceil(i / 2))}
I think that is not correct, in that list instances will appear as many times as they have users.

2017-11-10 12:02 UTC, houshuang commented
@lfaucon Is this done now? would be good to get it merged

2017-11-10 12:52 UTC, lfaucon approved these changes

2017-11-10 12:52 UTC, merged