Ac autocode dashboard
chili-epfl/FROG pull request #753
Opened 2018-01-09 18:17 UTC by Keylas

2018-01-11 09:30 UTC, lfaucon reviewed
@Keylas I tried to reduce the number of lines of code for the dashboard to make it easier to update in the future. You had some sort of optimisations implemented which were questionable as they required you to store in the dashboard data the code of all the students. I removed it, but now there will be a few more calls to `dataFn`.

2018-01-11 09:32 UTC, lfaucon requested changes

2018-01-11 09:32 UTC, lfaucon commented on ac/ac-autocode/src/Dashboard.jsx
> +    const o = Object.keys(props.users).reduce((acc, userId) => {
The viewer receives as props the list of users and instances. I think the dashboards should be based on instances. Logs also have the instanceId to be used in the merge function

2018-01-12 15:28 UTC, Keylas commented
The reason I was logging students' code was in case it would happen to become useful at some point (say the teacher would want to "probe" some code that have errors to get an idea of why his students are having trouble). This indeed led to weird test cases. The only sort of optimization it allowed was to not take into account multiple successive clicks on the buttons but even then it was not perfect.

2018-01-12 15:35 UTC, Keylas commented
- changed userId to insanceId because it does make more sense
remark: in preview, instances goes [0,1] while the log.instanceId are 1 and 2 so the graph is not correct.
- took Stian's #755 issue into account. It actually makes sense to have an activity without tests so functionalities that use it verify that props.config.tests is not undefined (most problem can from the fact that they assumed it to be [] initially whereas it seems to be undefined). Added a validateConfig to check that a non empty solution is provided when there are tests.

2018-01-16 06:49 UTC, lfaucon approved these changes

2018-01-16 06:49 UTC, merged