Improving Preview
chili-epfl/FROG pull request #896
Opened 2018-03-22 13:44 UTC by houshuang

2018-03-22 14:39 UTC, houshuang commented
Fixed that it was not updating multiple activities.

2018-03-23 08:53 UTC, lfaucon requested changes
I changed a bit the UI so that we can't scroll away from the top bar and that the config and activity scroll independently. 

The mergeFunction that fills reactive data from config is not called anymore. You can test it with ac-image (gallery)

2018-03-23 09:50 UTC, lfaucon approved these changes

2018-03-23 09:52 UTC, lfaucon commented
I see that this still works when we open the preview from the "eye" button in the activityType list, so even though it needs better UI and a lot of code refactoring, I'll merge it.

2018-03-23 09:52 UTC, merged